# Generated by Django 6.0.2 on 2026-07-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_add_rejected_resolved_status_admin_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownerregistrationquery",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
