# Generated by Django 6.0.2 on 2026-07-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online'), ('wallet', 'Wallet')], max_length=20, null=True),
        ),
    ]
