# Hand-written, not autogenerated. Migration 0001_initial declared "vehicle"
# as a required FK to parking.Vehicle and no later migration ever touched
# it — but the live "vehicle_id" column was changed to a plain varchar
# plate-string column outside Django's migrations at some point (see
# fix_fks.py / fix_db.py referenced in the merge audit). This migration
# only corrects Django's tracked STATE to match that reality; it runs no
# SQL. The genuinely new vehicle FK column is added for real in 0008.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_remove_booking_updated_at"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="booking",
                    name="vehicle",
                ),
                migrations.RemoveIndex(
                    model_name="booking",
                    name="bookings_entry_t_cf255c_idx",
                ),
                migrations.AddField(
                    model_name="booking",
                    name="legacy_vehicle_plate",
                    field=models.CharField(
                        blank=True, db_column="vehicle_id", max_length=50, null=True
                    ),
                ),
                migrations.AlterField(
                    model_name="booking",
                    name="entry_time",
                    field=models.DateTimeField(
                        blank=True, db_column="entry_datetime", null=True
                    ),
                ),
                migrations.AlterField(
                    model_name="booking",
                    name="exit_time",
                    field=models.DateTimeField(
                        blank=True, db_column="exit_datetime", null=True
                    ),
                ),
            ],
        ),
        # Choices/default are Python-level only for a plain CharField —
        # verified via sqlmigrate this emits no SQL, safe to run for real.
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("confirmed", "Confirmed"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
    ]
