# Generated by Django 6.0.2 on 2026-07-10 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_module", "0001_initial"),
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ailog",
            name="parking_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_logs",
                to="parking.parkingsite",
            ),
        ),
        migrations.AddField(
            model_name="cameraapikey",
            name="parking_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="camera_keys",
                to="parking.parkingsite",
            ),
        ),
    ]
