# Generated by Django 6.0.2 on 2026-07-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_module",
            "0005_ailog_assigned_slot_ailog_cropped_plate_ailog_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cameraapikey",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
