# Generated by Django 6.0.2 on 2026-07-10 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grace_period_minutes", models.IntegerField(default=10)),
                (
                    "overstay_rate_per_hour",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=8),
                ),
                ("reservation_lock_minutes", models.IntegerField(default=10)),
                ("max_booking_days", models.IntegerField(default=7)),
                ("cash_enabled", models.BooleanField(default=True)),
                ("easypaisa_enabled", models.BooleanField(default=True)),
                ("card_enabled", models.BooleanField(default=True)),
                ("refund_100_before_start", models.BooleanField(default=True)),
                ("refund_percent", models.IntegerField(default=50)),
                ("refund_window_minutes", models.IntegerField(default=30)),
                ("notify_new_owner", models.BooleanField(default=True)),
                ("notify_overstay", models.BooleanField(default=True)),
                ("notify_payment_received", models.BooleanField(default=True)),
                ("notify_manual_override", models.BooleanField(default=False)),
                ("require_phone_otp", models.BooleanField(default=True)),
                ("session_timeout_minutes", models.IntegerField(default=60)),
                ("max_login_attempts", models.IntegerField(default=5)),
                ("show_confidence_score", models.BooleanField(default=True)),
                ("show_owner_revenue", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "system_settings",
            },
        ),
        migrations.CreateModel(
            name="ParkingSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("capacity", models.IntegerField()),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("total_slots", models.IntegerField(blank=True, null=True)),
                ("total_floors", models.IntegerField(blank=True, null=True)),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "price_per_hour",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("city", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_sites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "parking_sites",
            },
        ),
        migrations.CreateModel(
            name="ParkingSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slot_number", models.CharField(max_length=20)),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("vip", "VIP"),
                            ("disabled", "Disabled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_occupied", models.BooleanField(default=False)),
                ("is_reserved", models.BooleanField(default=False)),
                (
                    "price_per_hour",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parking_site",
                    models.ForeignKey(
                        db_column="site_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="parking.parkingsite",
                    ),
                ),
            ],
            options={
                "db_table": "parking_slots",
                "unique_together": {("parking_site", "slot_number")},
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("plate_number", models.CharField(max_length=20, unique=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("car", "Car"), ("truck", "Truck")],
                        default="car",
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vehicles",
                "indexes": [
                    models.Index(
                        fields=["plate_number"], name="vehicles_plate_n_de64b1_idx"
                    )
                ],
            },
        ),
    ]
