# Generated by Django 6.0.2 on 2026-07-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingsite",
            name="extra_hour_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Rate charged per hour (or partial slab) after flat_hours. Falls back to global PARKING_EXTRA_PER_HOUR if not set.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parkingsite",
            name="flat_hours",
            field=models.PositiveIntegerField(
                default=4,
                help_text="Number of hours covered by the flat price (flat pricing only).",
            ),
        ),
        migrations.AddField(
            model_name="parkingsite",
            name="flat_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total price for the first `flat_hours` hours. Falls back to global PARKING_BASE_PRICE if not set.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parkingsite",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("flat", "Flat rate (first N hours) + hourly after"),
                    ("hourly", "Pure per-hour"),
                ],
                default="flat",
                max_length=10,
            ),
        ),
    ]
