"""
Django settings for sps_backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decimal import Decimal
from dotenv import load_dotenv
import os
load_dotenv()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sessions",
    "rest_framework",
    "accounts",
    "parking",
    "payments",
    "ai_module",
    "bookings.apps.BookingsConfig",
    "channels",
    "corsheaders",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist"
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

]

ROOT_URLCONF = "sps_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sps_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {'sslmode': 'require'},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL="accounts.User"

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Karachi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES':[
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES':[
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SIMPLE_JWT = {
    # THIS TOKEN EXPIRE AFTER 30 MIN OF LOGIN
    'ACCESS_TOKEN_LIFETIME':timedelta(minutes=30),
    # USER STAY LOGIN FOR 7 DAYS AFTER THIS HE HAVE TO SIGNIN AGAIN
    'REFRESH_TOKEN_LIFETIME':timedelta(days=7),
    # GENERATE TOKEN AFTER ACCESS TOKEN  IS REFRESHED
    'ROTATE_REFRESH_TOKENS':True,
    #OLD REFRESH TOKEN BLACKLISTED 
    'BLACKLIST_AFTER_ROTATION':True
}
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend', 
    'django.contrib.auth.backends.ModelBackend',  
]


MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'


#  Parking Pricing 
PARKING_BASE_PRICE = {
    "car":   50,
    "bike":  30,
    "truck": 80
}

PARKING_EXTRA_PER_HOUR = {
    "car":   10,
    "bike":  0,
    "truck": 10
}

PARKING_GRACE_PERIOD = 10  # minutes
PARKING_BASE_HOURS   = 4   # hours


# Twilio Settings
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_VERIFY_SID = os.getenv("TWILIO_VERIFY_SID")
TWILIO_AUTH_TOKEN  = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_PHONE       = os.getenv("TWILIO_PHONE")


# Email Settings

# Email Settings – Use environment variables for production.
# For local development, fallback to console backend if SMTP settings are absent.
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 1025))
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@smartpark.com")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", str(EMAIL_PORT == 587)).lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", str(EMAIL_PORT == 465)).lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5500",
    "http://127.0.0.1:5500",
    "http://localhost:5501",
    "http://127.0.0.1:5501",
    "http://127.0.0.1:5502",
    "http://localhost:5502",
]

CORS_ALLOW_CREDENTIALS = True

# NOTE: CORS_ALLOW_ALL_ORIGINS was removed here on purpose — both source
# backends set it to True, which silently overrides CORS_ALLOWED_ORIGINS
# above and allows every origin. Add real origins to CORS_ALLOWED_ORIGINS
# (or CORS_ALLOWED_ORIGINS env var) instead of re-adding this.

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-api-key",
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# WebSocket — Django Channels
ASGI_APPLICATION = "sps_backend.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv("REDIS_URL")],
        },
    },
}

# Payment gateway — ported from backend_ali (backend_friend had no gateway
# abstraction, only simulated instant-success payments).
# Gateway switch — change to 'simpaisa' when ready for production
PAYMENT_GATEWAY = os.getenv("PAYMENT_GATEWAY", "mock")

# Public backend URL, used to build gateway callback/webhook URLs.
# backend_ali had this hardcoded to a personal ngrok tunnel; it must come
# from the environment so it can point at whatever host is actually deployed.
BACKEND_URL = os.getenv("BACKEND_URL", "http://127.0.0.1:8000")

# Simpaisa credentials — leave empty in .env until issued by Simpaisa
SIMPAISA_API_KEY = os.getenv("SIMPAISA_API_KEY", "")
SIMPAISA_SECRET_KEY = os.getenv("SIMPAISA_SECRET_KEY", "")
SIMPAISA_MERCHANT_ID = os.getenv("SIMPAISA_MERCHANT_ID", "")
SIMPAISA_BASE_URL = os.getenv("SIMPAISA_BASE_URL", "https://sandbox.simpaisa.com/api/v1")

# Platform commission taken from each wallet-paid booking (10%)
PLATFORM_COMMISSION = Decimal(os.getenv("PLATFORM_COMMISSION", "0.10"))
